trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default'
  demands:
  - agent.name -equals ec2-docker-cicd-agent


steps:
  - checkout: self
    displayName: "Syncing code updates from remote to local..."

  - script: |
      echo "Changing to repo directory..."
      cd $(Agent.BuildDirectory)/s
      echo "Current directory: $(pwd)"
      ls -al
      echo "Executing Ansible Playbook..."
      ansible-playbook -i ansible/inventory.ini ansible/deploy_docker_container.yml
    displayName: "Execute Ansible Playbook"


  - script: |
      echo "Deployment process completed."
    displayName: "Deployment Completed"