# ----------------------- Docker deployment CICD yaml BEGIN ----------------------------

trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default'
  demands:
  - agent.name -equals ec2-docker-cicd-agent


steps:
  - checkout: self
    displayName: "Syncing code updates from remote to local..."

  - script: |
      echo "Changing to repo directory..."
      cd $(Agent.BuildDirectory)/s
      echo "Current directory: $(pwd)"
      ls -al
      echo "Executing Ansible Playbook..."
      ansible-playbook -i ansible/inventory.ini ansible/deploy_docker_container.yml
    displayName: "Execute Ansible Playbook"

# ----------------------- Docker deployment CICD yaml END ----------------------------




# --------------------------- Test script BEGIN  ---------------------------


# trigger:
# - main

# pool:
#  name: 'Default'
#  demands:
#  - agent.name -equals ec2-docker-cicd-agent


# steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'


# --------------------------- Test script END  -----------------------------