---
- name: Docker Container Deployment
  hosts: ec2
  become: yes

  tasks:
    - name: Copy project files to ec2 instance
      ansible.builtin.copy:
        src: ../
        dest: /home/ubuntu/webapp/
        mode: 0755

    - name: Build Docker image
      community.docker.docker_image:
        name: dockerized_webapp
        build:
          path: /home/ubuntu/webapp
        source: build

    - name: Run Docker container
      community.docker.docker_container:
        name: dockerized_webapp_container
        image: dockerized_webapp
        state: started
        restart_policy: always
        ports:
          - "80:80"

