- name: Deploy Dockerized Web App on EC2
  hosts: localhost
  become: true
  tasks:
    - name: Build Docker image
      command: docker build -t webapp:latest .
      args:
        chdir: /home/ubuntu/desktop_contents/_work/1/s

    - name: Stop existing container
      command: docker stop webapp || true

    - name: Remove existing container
      command: docker rm webapp || true

    - name: Run container
      command: docker run -d -p 8080:8080 --name webapp webapp:latest


