- name: Deploy Dockerized Web App on EC2
  hosts: localhost
  become: true
  tasks:
    - name: Build Docker image
      command: docker build --no-cache -t webapp:latest .
      args:
        chdir: /home/ubuntu/desktop_contents/_work/1/s

    - name: Stop existing container
      command: docker stop webapp
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm webapp
      ignore_errors: yes

    - name: Run container with restart policy
      command: docker run -d -p 8080:80 --name webapp --restart unless-stopped webapp:latest
      ignore_errors: yes
